# Generated by Django 2.2.1 on 2020-06-08 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('subtitle', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('thumbnail', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=64)),
                ('brand_name', models.CharField(max_length=64)),
                ('category_name', models.CharField(max_length=64)),
                ('is_deleted', models.BooleanField()),
                ('is_published', models.BooleanField()),
                ('is_new', models.BooleanField()),
                ('is_recommended', models.BooleanField()),
                ('is_verified', models.BooleanField()),
                ('sale_volume', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('unit', models.CharField(max_length=16)),
                ('detail_pic_album', models.CharField(max_length=255)),
                ('detail_title', models.CharField(max_length=255)),
                ('detail_description', models.TextField()),
                ('detail_html', models.TextField()),
                ('detail_mobile_html', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('selection_type', models.IntegerField()),
                ('input_type', models.IntegerField()),
                ('input_enum_list', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'product_attribute',
                'verbose_name_plural': 'product_attributes',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('attribute_count', models.IntegerField()),
                ('parameter_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'product_attribute_category',
                'verbose_name_plural': 'product_attribute_categories',
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('first_letter', models.CharField(max_length=8)),
                ('product_count', models.IntegerField()),
                ('logo', models.CharField(max_length=255)),
                ('brand_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'product_brand',
                'verbose_name_plural': 'product_brands',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('product_unit', models.CharField(max_length=64)),
                ('icon', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.ProductCategory')),
            ],
            options={
                'verbose_name': 'product_category',
                'verbose_name_plural': 'product_categories',
            },
        ),
        migrations.CreateModel(
            name='ProductVerifyingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('detail', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifying_records', to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('low_stock_threshold', models.IntegerField()),
                ('customizable_specs', models.CharField(max_length=255)),
                ('sale_volume', models.IntegerField()),
                ('detail_pic', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStockOperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old', models.IntegerField()),
                ('new', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_operation_logs', to='product.ProductVariant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPriceOperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_operation_logs', to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategoryAttributeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='product.ProductAttributeCategory')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category_attributes', to='product.ProductCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.Product')),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.ProductAttribute')),
            ],
            options={
                'verbose_name': 'product_attribute_value',
                'verbose_name_plural': 'product_attribute_values',
            },
        ),
        migrations.AddField(
            model_name='productattribute',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.ProductAttributeCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.ProductAttributeCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.ProductBrand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.ProductCategory'),
        ),
    ]
